general:
  kafka-topic: trader-updates

spring:
  Kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: midas-core-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
  jpa:
    hibernate:
      ddl-auto: update
